# Generated by Django 4.1.5 on 2023-01-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("country", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256)),
                ("gender", models.CharField(max_length=256)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=256)),
                ("job_title", models.CharField(max_length=256)),
                ("is_current_job", models.BooleanField(default=True)),
                ("company_email", models.EmailField(max_length=256)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.person"
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
