# Generated by Django 4.1.5 on 2023-01-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
    ]
